### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by timonmasberg** [kordis-leitstelle/kordis#3]
As we aim to be “open-source” we should choose a license pretty quickly to have no liability or warranty issues. Furthermore, we need to discuss if we want to be truly open source or license Kordis under a non-commercial license which would prevent someone to sell Kordis or create a SaaS layer over it. An example license would be the Elastic License, which technically is not an open-source license!

My choice would be a [General Public License](https://choosealicense.com/licenses/agpl-3.0/) that specifies that source code of distributed material from Kordis must be available under the same license, which, I think, is more than fair.

**Comment by JSPRH** [comment]
Sounds good to me!
